name: .NET Build test (Linux)

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v1
      
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build Solution
      run: |
        dotnet build AnthillNet.sln
  test:
    runs-on: windows-latest
    needs: build
    env:
      config: 'Release'

    steps:
    - uses: actions/checkout@v2

    - name: Set PR Number
      id: PRNUMBER
      if: ${{ github.event_name == 'pull_request' }}
      uses: kkak10/pr-number-action@v1.3

    - name: TCP Test
      uses: zyborg/dotnet-tests-report@v1
      with:
        project_path: TestingLab
        report_name: TCP Test #${{steps.PRNUMBER.outputs.pr}} (${{github.run_number}})"
        report_title: AnthillNet Test
        github_token: ${{ secrets.GITHUB_TOKEN }}
